### ISSUE TITLE
[FEATURE] Add Towny Support

### ISSUE THREAD

**Issue by LcyDev** [SoKnight/PEconomy#10]
https://github.com/TownyAdvanced/Towny/wiki/TownyAPI#getting-started-with-towny-and-your-ide

**Comment by SoKnight** [comment]
Hello.
What do you mean?

**Comment by LcyDev** [comment]
Hey, i'm not really sure what it means but from what i was told, this is something that TNE had and basically it allows you to do direct transactions to any Towns or Nations.

Basically being able to do some sort of `/pay {town/nation}`, I don't really know if it's possible since it's really vague the info

I guess you can check it out and if it isn't viable close this.

Anyways, possible or not, i'm going to use this plugin since it's the best one i could find ;)
Along with BetterEconomy for the items.

**Comment by ConaII** [comment]
I think the "support feature" was that you could /pay directly to the Town or Nation

**Comment by SoKnight** [comment]
Hmm, it sounds like a something interesting.
I haven't played on any servers with Towny yet, but I will try to add support of direct payments to towns/nations when I find out about Towny gameplay and dev features.
Thx for your suggestion, I'll add that to the list in repo README.
If you have any other suggestions then create a new issue please.
