### ISSUE TITLE
Disable transaction messages

### ISSUE THREAD

**Issue by BeaSHyneGG** [SoKnight/PEconomy#14]
Hi! I need to remove chat messages about transactions. It seems that this is not in the config. Could you please add it?

**Comment by SoKnight** [comment]
> chat messages about transactions

Hi! What do you mean? Can you send a screenshot, please?

**Comment by BeaSHyneGG** [comment]
I'm about messages, when a player receives or has money taken from them, it is shown in the chat. I would like to hide these messages.

P.s: I'm not at home right now, I'll come back and specify exactly what I mean and attach a screenshot

**Comment by SoKnight** [comment]
Try putting (`''`) in the value of the messages you want to hide from the chat in the localization file messages_XX.yml.
Also you can try to set value `@#DISABLED` for these message keys.

**Comment by BeaSHyneGG** [comment]
Sorry for the long answer. I'll try today and answer in the next few hours. Empty quotes didn't help, I used them before. The chat displays empty message. I'll look at the second option again.

**Comment by BeaSHyneGG** [comment]
Oh yeah, that helped! Thanks for the help, we can close the issue!
