### ISSUE TITLE
CompletableFuture may swallow exceptions

### ISSUE THREAD

**Issue by A248** [SoKnight/PEconomy#2]
### Introduction

I picked a class in the source code to look at, and came here:

https://github.com/SoKnight/PEconomy/blob/8784a758ef7241016f9e194abc2811c124994de7/src/main/java/ru/soknight/peconomy/listener/PlayerJoinListener.java#L33-L39

While this seems like harmless code, it is actually equally harmful as ignoring exceptions, as in the following code:

```java
try {
   // Do stuff
} catch (Throwable ignored) {
  // Exception is lost!
}
```

### Explanation

CompletableFuture is infamous for swallowing exceptions. Run the following code snippet. No exception will be printed:

```java
public class FutureMain {
  public static void main(String[] args) {
    CompletableFuture.supplyAsync(() -> {
        return true;
    }).thenAccept((value) -> {
        throw new RuntimeException();
    });
  }
}
```

### Summary

The issue is that if an exception occurs inside thenAccept, it will not be logged anywhere. For example, this exception will never be shown:

```java
databaseManager.getWallet(name).thenAccept(wallet -> {
  throw new IllegalStateException();
});
```

**Comment by SoKnight** [comment]
Thank you for this issue but what do you actually suggest?
Why exceptions in this listener should not be ignored? Explain please.

**Comment by A248** [comment]
Exceptions shouldn't be ignored for the same reason you shouldn't be wrapping every code block in `try { } catch (Throwable ignored) {}`.

Exceptions are your friends, not your enemies. They provide valuable information about what went wrong and when. Lost exceptions harm the quality of your code as bugs go unnoticed. Even if you knew your current code did not throw any, future code changes can easily introduce new bugs.

It would be ludicrous to write your code to ignore and hide all exceptions. The easiest bugs to fix are the ones which make themselves clear.

**Comment by SoKnight** [comment]
Okay, you're right.
Issued code snippet actually shouldn't throw any exceptions apart from database queries exceptions.
I'll think about it, thanks again.
