### ISSUE TITLE
currency convert

### ISSUE THREAD

**Issue by dancebunny98** [SoKnight/PEconomy#3]
I study English superficially from Russia. In the future, forgive my oblique language.

My idea is to let the player choose (command or menu) which currency he wants to transfer from (accordingly, not free of charge, but with a commission.)

Let's imagine the following situation. We have the main currency, then it can or cannot (depending on the setting) be converted into the second (donate currency) but with the condition (10> 1) and the second currency (50> 500).

/peco convert <currency> <amount> <currency> or /peco convert <currency> <amount> for 2 currency wallet.

**Comment by SoKnight** [comment]
Yes, thank you, very good suggestion :)
Somebody other was suggested that already, but I forgot his concept.
Now I have your concept and will use that)
Please, wait for one of next releases where this feature will be introduced.

p.s.: you can use Russian language here, I am from Russia too :)

**Comment by dancebunny98** [comment]
How soon will this be implemented?

**Comment by SoKnight** [comment]
> How soon will this be implemented?

Maybe on this week.

**Comment by dancebunny98** [comment]
> Maybe on this week.

really looking forward to it.

**Comment by Dancbeunny98** [comment]
`UDP: Комментарий потом отредактирую на /del  `

Вы не желаете пойти к нам на проект?

**Comment by SoKnight** [comment]
> Вы не желаете пойти к нам на проект?

Спасибо за приглашение, но на данный момент я уже работаю в одной компании.

**Comment by dancebunny98** [comment]
Когда будет обновление?

**Comment by SoKnight** [comment]
> Когда будет обновление?

Пока не могу сказать, пока загружен работой.
В эти выходные постараюсь выпустить.

**Comment by SoKnight** [comment]
Feature added in the last release, issue closed.
