### ISSUE TITLE
Vault hook uses the wrong config

### ISSUE THREAD

**Issue by MrLetsplay2003** [SoKnight/PEconomy#6]
When trying to use PEconomy with Vault, it will always state
`[PEconomy] Vault default currency is not specified, ignoring it.`
because it tries to look for the `vault.currency` setting in the wrong config file (it looks in the `config.yml` instead of the `currencies.yml`).

When setting the `vault.currency` setting in the `config.yml` everything works as intended.

I believe this is caused by [this line](https://github.com/SoKnight/PEconomy/blob/7a551c550c7341276c59a8f5461a4a3c3a69a142/src/main/java/ru/soknight/peconomy/configuration/CurrenciesManager.java#L103), which uses the configuration returned by `getConfig()` instead of the one provided by `AbstractConfig#getBukkitConfig()`.

**Comment by SoKnight** [comment]
Fixed in [PEconomy v2.7.1](https://github.com/SoKnight/PEconomy/releases/tag/2.7.1).
Thanks you for this report.
