### ISSUE TITLE
pay and add command defaulting to using "dollars" as currency instead of custom one

### ISSUE THREAD

**Issue by HyperlyBola** [SoKnight/PEconomy#7]
![1XyiwWYWYI](https://user-images.githubusercontent.com/50128850/149854931-89101037-3e97-451f-a95a-f847148800a4.png)

Is there no way to fix this, or did I miss something in the config?

**Comment by SoKnight** [comment]
Hello, do you configure your custom currency in `currencies.yml`?
After that you should reload the plugin configurations: `/peco reload`.
Please, say me how to reproduce that.

**Comment by SoKnight** [comment]
@HyperlyBola

**Comment by SoKnight** [comment]
Not actual, or reopen this issue later
