### ISSUE TITLE
Not respecting config.

### ISSUE THREAD

**Issue by RebelMythik** [SoKnight/PEconomy#8]
The disable vault-hook option on the config is not respected at all. PEconomy is still hooking into vault after the config option has been disabled.

**Comment by RebelMythik** [comment]
https://imgur.com/a/5F0ey7F
https://imgur.com/a/FDk416S

**Comment by SoKnight** [comment]
Thank you for this report.
This bug should be fixed in the [PEconomy v2.7.3](https://github.com/SoKnight/PEconomy/releases/tag/2.7.3).
Please, check that and give your feedback again.
